import org.apache.commons.dbcp2.BasicDataSource
import org.springframework.jdbc.core.JdbcTemplate

object Conexao {
    var JdbcTemplate:JdbcTemplate? = null

        get() {
            if (field == null){
                val dataSource = BasicDataSource()
                dataSource.driverClassName = "org.h2.Driver"
                dataSource.url = "jdbc:h2:mem:pizzaria"
                dataSource.username = "sa"
                dataSource.password = ""

                val novoJdbcTemplate = JdbcTemplate(dataSource)
                field = novoJdbcTemplate
            }
                return field
        }

    fun criarTabelas(){
       JdbcTemplate!!.execute(
           """create table filmes (
               id int GENERATED BY DEFAULT AS IDENTITY primary key,
               nome varchar(50),
               diretor varchar(30),
               indicadoOscar boolean,
               custoProducao Double
               );
           """
       )
    }
}