import javax.swing.JOptionPane
import org.apache.commons.dbcp2.BasicDataSource
import org.springframework.jdbc.core.BeanPropertyRowMapper
import org.springframework.jdbc.core.JdbcTemplate

fun main() {

    val dataSource = BasicDataSource()
    dataSource.driverClassName = "org.h2.Driver"
    dataSource.url = "jdbc:h2:mem:pizzas"
    dataSource.username = "sa"
    dataSource.password = ""

    val jdbcTemplate = JdbcTemplate(dataSource)

    jdbcTemplate.execute(
        """
        create table Pizza (
            id INT GENERATED BY DEFAULT AS IDENTITY primary key,
            sabor varchar(50) not null,
            preco float(7,2), 
            quantidade INT
        )
    """.trimIndent()
    )
    val pedidos = mutableListOf<Pizza>()
    while (true) {

        var pergunta = JOptionPane.showInputDialog(
            null,
            "Você quer cadastrar uma nova pizza?S para sim ou qualquer coisa para não"
        ).toString()

        if (pergunta.uppercase() == "s") {

            val pizza = Pizza()
            pizza.sabor = JOptionPane.showInputDialog(null, "Qual o sabor da pizza?").toString()

            pizza.preco = JOptionPane.showInputDialog(null, "Qual o preço da pizza?").toDouble()

            pizza.quantidade = JOptionPane.showInputDialog(null, "Qual a quantidade de pizzas?").toInt()
            pedidos.add(pizza)

            jdbcTemplate.update(
                """
                insert into pizza (sabor, preco, quantidade) VALUES ('${pizza.sabor}', ${pizza.preco}, ${pizza.quantidade})
                """.trimIndent()
            )
        } else {
            break
        }
    }
    var codigo = JOptionPane.showInputDialog(
        null,
        "Qual pizza quer vender? Digite de 1 a ${pedidos.size}").toInt()

    if (codigo < 0){
        JOptionPane.showMessageDialog(null, "Insira um valor válido")
    }else {
        val pedidosConsultados: List<Pizza> = jdbcTemplate.query(
            "select quantidade from pizza WHERE id = ${codigo};",
            BeanPropertyRowMapper(Pizza::class.java)
        )

        if (pedidosConsultados > 0){
            jdbcTemplate.update(
                """
                    update pizza set quantidade = ${pedidosConsultados -1} WHERE id = ${codigo}
                """
            )

            JOptionPane.showMessageDialog(null, "A quantidade da pizza foi atualizada para $pedidosConsultados")
        }else {
            JOptionPane.showMessageDialog(null, "Não existe mais dessa pizza no estoque")
        }
    }
    }


